version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/code_execution
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=code_execution
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 